---
title: "Shiny Study results"
author: 
  - Berta Raventós & Melissa Leung 
institute: 
  - Ermasmus Medical Center
format:
  html:
    embed-resources: true
editor: visual
echo: true
eval: true
toc: true
warning: false
---

## Introduction

In this part of the tutorial, we will explore Shiny Apps to see how we can review study results. The results that we will see are from two studies on paracetamol prescribing and paracetamol overdose in Europe (1,2). Both were cohort studies aimed to estimated the yearly incidence rates of paracetamol prescribing and overdose, as well as the period prevalence of paracetamol prescribing. Moreover, characteristics of individuals with paracetamol overdose were described.

## Exercice: DrugExposureDiagnostics

For this exercise, we will review a ShinyApp with DrugExposureDiagnostics (3) results for hypothetical data sources participating in the study. You will explore the Shiny app in groups of four. Approach the results from a reviewer’s perspective and try to identify aspects that might be critical for the study.

Most sections of the Shiny app allow you to filter results (e.g., by data source) and generate plots. Be sure to use these features to help you review the results effectively.

## Useful links

-   Shiny App with DrugExposureDiagnostics results: <to add>

### Exercice 1

1.1. Begin by reviewing the "Ingredient Concepts" section.The drop_down menu "Variable" allows to explore plots stratified by drug, concept_class, and dose_form. Which is the drug (concept) with most counts across data sources?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Database 1 & 6: Acetaminophen 500 MG; Database 2: Acetaminophen 125MG; Database 3: Acetaminophen; Database 7: Acetaminophen 1000 MG Oral Tablet; Database 8: Acetaminophen/Tramadol Tablet for Oral Suspension.
:::

1.2. For the study, we will need to stratify results by dose form. Are oral formulations the most common across the data sources? Examine the plots and record any insights or findings that catch your attention.

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

In general, oral forms predominate across data sources (e.g., tablets, capsules, suspensions). In Database 2, rectal suppositories are the most common. In Database 5, the “unknown” category predominates, followed by injections. Injections also rank second in Database 1.
:::

### Exercice 2

2.1. Review the "Drug routes" section and explore the routes captured in the data. Do these align with those observed by dose form?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

In most cases, yes, as the oral route predominates across the data sources. However, Databases 2 and 7 contain no information on the route, and in Database 5, many records do not have a matching concept.
:::

2.2. Review "Drug variables missing". What is the percentatge of missings in Database 5? Filter results by database and value ("n_missing_route_concept_id")

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

From the sample analysed, the percentage of missings is approximately 42% in Database 5.
:::

2.3. In this database, which concept (drug_concept_id; drug) has more records with missing values? To do so, use the same filters as the previous question and click on "by concept_id".

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Most records with missing data correspond to the ingredient-level code (1125315, acetaminophen), which provides no information beyond the ingredient name.
:::

### Exercice 3

3.1. Review the "Drug types" section. What kinds of records are present in the data sources? Is there anything unusual or noteworthy? How would you handle it?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Most records are EHR, EHR prescription/dispensing, or registry. In Database 5, some records are labeled as NLP. It would be recommended to discuss with the data partner how these records were generated.
:::

### Exercice 4

4.1. Review the "Drug Source Concepts" section. Is it possible to examine source concepts in all databases? If not, which databases do not allow this?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Database 1, 5, and 7 have no drug_source_concept_id. In database 1, 2, and 7, some drug_source_values are available (verbatim value from the source data).
:::

4.2. In Databases 7 and 8, it is possible to review drug_source_values, as they use ATC codes as source values. Examine the source concepts for these two data sources. Do you notice any inconsistencies or mismatches between the source values and the mapped concepts?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

For database 8, we see source values for drugs that are not related to paracetamol, such as diclofenac, ibuprofen, ketoprofen, etc.
:::

### Exercice 5

5.1.Examine the "Drug exposure duration" section, focusing on the minimum, median, and percentile values. Is there anything that catches your attention?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Median and percentile values are the same in Database 2 and 8.
:::

5.2. How would you explain the results for Data Sources 2 and 8? What would you do in this case?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

The fact that all values are identical suggests that the databases might lack actual duration information, possibly defaulting to 30 days for all records. If we are conducting a multi-database study, confirming this with the data partner would be recommended.
:::

5.3. The results for Data Sources 1 and 5 make sense given the healthcare settings covered by these sources. What kind of data do you think they contain?

::: {.callout-tip appearance="simple" collapse="true"}
## Answer

Median duration is 1 and 3 days, which could be reasonable if these data sources have data from inpatient data only.
:::

5.4. In this study, we aim to calculate prevalence of paracetamol prescribing. How the recording of duration can impact our results?

## References

1.  DARWIN EU® – Paracetamol prescribing and paracetamol overdose in Europe: a descriptive analysis of trends and patient characteristics (EUPAS1000000329), https://catalogues.ema.europa.eu/node/4230/administrative-details
2.  DARWIN EU® – Paracetamol prescribing and paracetamol overdose in Europe: a descriptive analysis of trends and patient characteristics (EUPAS1000000584), https://catalogues.ema.europa.eu/node/4485/administrative-details
3.  Inberg G, Burn E, Burkard T (2026). DrugExposureDiagnostics: Diagnostics for OMOP Common Data Model Drug Records. R package version 1.1.6, https://darwin-eu.github.io/DrugExposureDiagnostics/.
